server:
  port: 9999

docusafe:
  storeconnection:
    filesystem:
      basedir: affe
    no-minio:
      url: http://192.168.178.60:9000
      accesskey: simpleAccessKey
      secretkey: simpleSecretKey
      rootbucket: affe
      no-encryptionpassword: null
    no-mongo:
      mongoURI: mongodb://192.168.178.60:32770
    no-amazons3:
      url: http://192.168.178.60:9000
      accesskey: simpleAccessKey
      secretkey: simpleSecretKey
      encryptionpassword: Affenpapier1'