server:
  port: 9999

docusafe:
  storeconnection:
    filesystem:
      basedir: target/FILESYSTEM
      encryptionpassword: null
    no-minio:
      url: http://192.168.178.60:9000
      accesskey: simpleAccessKey
      secretkey: simpleSecretKey
      rootbucket: affe
      no-encryptionpassword: null
    no-mongo:
      database: admin
      host: 192.168.178.60
      port: 32770
      user: null
      password: null
    no-amazons3:
      url: http://192.168.178.60:9000
      accesskey: simpleAccessKey
      secretkey: simpleSecretKey
      encryptionpassword: Affenpapier1'